server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: 'demo'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true